# Generated by Django 3.2.2 on 2022-01-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0003_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='title2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
